name=MqttDevice
version=1.0.0
author=Jo L
maintainer=Jo L
sentence=Biblioteca MQTT para Arduino com suporte a ESP32/PICO.
paragraph=Esta biblioteca implementa um agente MQTT para dispositivos Arduino, incluindo funcionalidades para conectar, publicar, subscrever e gerir eventos MQTT.
category=Communication
url=https://github.com/Jo4096/MqttDevice
architectures=*
